apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kustomize-namespace
  annotations:
    description: |
      This task takes the result of a crane-apply and structure it as an
      application base kustomization.
spec:
  # These are all required parameters to the task when we write a Pipeline using
  # this task, we must ensure that these parameters are supplied.
  params:
    - name: dest-namespace
      type: string
      description: The namespace we are importing to.
  steps:
    - name: kustomize-namespace
      image: quay.io/djzager/crane-runner:alpha
      script: |
        # Make common base directory
        kustomize_base_dir="$(workspaces.kustomize.path)/base"
        mkdir -p ${kustomize_base_dir}

        # Fill in base kustomization.yaml
        base_kustomization="${kustomize_base_dir}/kustomization.yaml"
        echo "apiVersion: kustomize.config.k8s.io/v1beta1" > "${base_kustomization}"
        echo "kind: Kustomization" >> "${base_kustomization}"
        echo "" >> "${base_kustomization}"
        echo "resources:" >> "${base_kustomization}"
        # Find the resources from the apply step
        yamls=$(find $(workspaces.apply.path)/resources -type f -name \*.yaml)
        for yaml in ${yamls}; do
          cp ${yaml} ${kustomize_base_dir}
          file=$(basename "${yaml}")
          echo "- ${file}" >> "${base_kustomization}"
        done
        cat "${base_kustomization}"

        # Fill in kustomization.yaml
        kustomization="$(workspaces.kustomize.path)/kustomization.yaml"
        echo "apiVersion: kustomize.config.k8s.io/v1beta1" > "${kustomization}"
        echo "kind: Kustomization" >> "${kustomization}"
        echo "" >> "${kustomization}"
        echo "namespace: $(params.dest-namespace)" >> "${kustomization}"
        echo "" >> "${kustomization}"
        echo "resources:" >> "${kustomization}"
        echo "- base/" >> "${kustomization}"
        cat "${kustomization}"

        # Verify it builds
        kustomize build $(workspaces.kustomize.path)/
  # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#using-workspaces-in-tasks
  workspaces:
    - name: apply
      description: |
        This is the folder where we will store the results of crane apply.
      mountPath: /var/crane/apply
    - name: kustomize
      description: |
        This is where the kustomize related manifests will be saved.
